from typing import Protocol, Self

class GraphemeClusterIterator(Protocol):
    def __new__(self, s: str, extended: bool) -> Self: ...
    def __init__(self, s: str, extended: bool) -> None: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> str: ...

def grapheme_clusters(s: str, extended: bool = True) -> list[str]: ...
